### ISSUE TITLE
Watcher takes really long on 1k-files projects

### ISSUE THREAD

**Issue by tobias-trozowski** [phly/php-qa-watch#5]
I'm currently working on a project with just 1k files. It's not that big but seems to be big enough to get some issues with the watcher which takes a long time for indexing.

Is there any special reason why you wait for the scan to complete before triggering the check program?
Otherwise i would suggest to remove this:
```js
if (! scanComplete) {
    /* Do nothing until we've finished scanning files */
    return;
}
```

**Comment by weierophinney** [comment]
IIRC, it was triggering once for each file until it completed the scan, and
then would wait for file system changes.

**Comment by tobias-trozowski** [comment]
mhm ok. thanks for respond.
Seems to be a bug in the watcher from chokidar itself.
